config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  match "/about_us"=>"home#about_us", :as => :about_us
  match "/contacts"=>"home#contacts", :as => :contacts
  match "/otzyvy"=>"home#otzyvy", :as => :otzyvy
  match "/certificates"=>"home#certificates", :as => :certificates
  match '/vendors'=> "vendors#index"

  # scope :service do
	match "service/get_products"=> "service#get_products", as: :get_products
  # end
  

end

app/controllers/spree/orders_controller_decorator.rb
Spree::OrdersController.class_eval do
  def populate
    @order = current_order(true)

    params[:products].each do |product_id,variant_id|
      quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
      quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
      @order.add_variant(Spree::Variant.find(variant_id), quantity) if quantity > 0
    end if params[:products]

    params[:variants].each do |variant_id, quantity|
      quantity = quantity.to_i
      @order.add_variant(Spree::Variant.find(variant_id), quantity) if quantity > 0
    end if params[:variants]

    fire_event('spree.cart.add')
    fire_event('spree.order.contents_changed')
    respond_with(@order) do  |format| 
    	format.html { redirect_to cart_path } 
    	format.js
    end
  end
end

app/controllers/spree/taxons_controller_decorator.rb
Spree::TaxonsController.class_eval do

  def show
    @taxon = Spree::Taxon.find_by_permalink!(params[:id])
    return unless @taxon

    if params[:sort] 
    	session[:sort] = params[:sort]
    else
    	session[:sort] = 'name'
    end
    @searcher = Spree::Config.searcher_class.new(params.merge(:taxon => @taxon.id, order_by: 'sku'))
    @products = @searcher.retrieve_products

    respond_with(@taxon) do |format|
    	format.html
    	format.js
    end
  end

end

app/controllers/spree/vendors_controller.rb
#encoding: UTF-8;
module Spree
  class VendorsController < Spree::BaseController
    
    def index
		@vendors=Spree::Taxon.find_by_name("Производители")
  		@taxonomy = Spree::Taxonomy.find{|t| t.name.eql?('Категории')}
  		@taxon=@taxonomy.root
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper
    def link_to_cart(text = nil)
      return "" if current_page?(cart_path)

      text = text ? h(text) : t('cart')
      css_class = nil

      if current_order.nil? or current_order.line_items.empty?
        text = "#{text}: (#{t('empty')})"
        css_class = 'empty'
      else
        text = "#{text}: (#{current_order.item_count})  <span class='amount'>#{order_subtotal(current_order)}</span>".html_safe
        css_class = 'full'
      end

      link_to text, cart_path, :class => css_class
    end

    def link_to_cart_with_image(text = nil)
      return "" if current_page?(cart_path)

      text = text ? h(text) : t('cart')
      css_class = nil

      if current_order.nil? or current_order.line_items.empty?
        text = image_tag 'bag.png'
        css_class = 'empty'
      else
        text=image_tag 'bag.png'
        text<<link_to(current_order.item_count,cart_path ,class:'big_link')
        text << "<p class='to_center'><span class='amount'>#{order_subtotal(current_order)}</span></p>".html_safe
        css_class = 'full'
      end

      link_to text, cart_path, :class => css_class
    end

    def order_subtotal(order, options={})
      options.assert_valid_keys(:format_as_currency, :show_vat_text)
      options.reverse_merge! :format_as_currency => true, :show_vat_text => true

      amount =  order.total

      options.delete(:format_as_currency) ? number_to_currency(amount) : amount
    end

    def todays_short_date
      utc_to_local(Time.now.utc).to_ordinalized_s(:stub)
    end

    def yesterdays_short_date
      utc_to_local(Time.now.utc.yesterday).to_ordinalized_s(:stub)
    end

    # human readable list of variant options
    def variant_options(v, allow_back_orders = Spree::Config[:allow_backorders], include_style = true)
      ActiveSupport::Deprecation.warn('variant_options method is deprecated, and will be removed in 0.80.0', caller)
      list = v.options_text

      # We shouldn't show out of stock if the product is infact in stock
      # or when we're not allowing backorders.
      unless (allow_back_orders || v.in_stock?)
        list = if include_style
        content_tag(:span, "(#{t(:out_of_stock)}) #{list}", :class => 'out-of-stock')
      else
        "#{t(:out_of_stock)} #{list}"
      end
    end

    list
  end

  Spree::Image.attachment_definitions[:attachment][:styles].each do |style, v|
    define_method "#{style}_image" do |product, *options|
      options = options.first || {}
      if product.images.empty?
        image_tag "noimage/#{style}.png", options
      else
        image = product.images.first
        options.reverse_merge! :alt => image.alt.blank? ? product.name : image.alt
        image_tag image.attachment.url(style), options
      end
    end
  end

  def meta_data_tags
    object = instance_variable_get('@'+controller_name.singularize)
    meta = { :keywords => Spree::Config[:default_meta_keywords], :description => Spree::Config[:default_meta_description] }

    if object.kind_of?(ActiveRecord::Base)
      meta[:keywords] = object.meta_keywords if object[:meta_keywords].present?
      meta[:description] = object.meta_description if object[:meta_description].present?
    end

    meta.map do |name, content|
      tag('meta', :name => name, :content => content)
    end.join("\n")
  end

  def body_class
    @body_class ||= content_for?(:sidebar) ? 'two-col' : 'one-col'
    @body_class
  end

  def logo(image_path=Spree::Config[:logo])
    link_to image_tag(image_path), root_path
  end

  def flash_messages
    [:notice, :error].map do |msg_type|
      if flash[msg_type]
        content_tag :div, flash[msg_type], :class => "flash #{msg_type}"
      else
        ''
      end
    end.join("\n").html_safe
  end

  def breadcrumbs(taxon, separator="&nbsp;&raquo;&nbsp;")
    return "" if current_page?("/") || taxon.nil?
    separator = raw(separator)
    crumbs = [content_tag(:li, link_to(t(:home) , root_path) + separator)]
    if taxon
      crumbs << content_tag(:li, link_to(t(:products) , products_path) + separator)
      crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor)) + separator) } unless taxon.ancestors.empty?
      crumbs << content_tag(:li, content_tag(:span, link_to(taxon.name , seo_url(taxon))),:class=>"active")
    else
      crumbs << content_tag(:li, content_tag(:span, t(:products)))
    end
    crumb_list = content_tag(:ul, raw(crumbs.flatten.map{|li| li.mb_chars}.join), :class => 'my_breadcrumb')

  end


  def taxon_block(root_taxon, current_taxon, max_level=2)
    return '' if max_level < 1 || root_taxon.children.empty?
    head_block = (max_level==2) ? true : false

    content_tag :ul, :class =>head_block ? "block_tax-list" : "sub_block_tax" do
      root_taxon.children.map do |taxon|
        css_class = head_block ? 'span4' : 'sub_cat'
        content_tag :li, :class => css_class do

          link_to(taxon.name, seo_url(taxon)) +
          taxon_block(taxon, current_taxon, max_level - 1)
        end
      end.join("\n").html_safe
    end
  end

  def taxons_tree(root_taxon, current_taxon, max_level = 1)
    # raise max_level.to_yaml

    # max_level=2
    # debugger
    return '' if max_level < 1 || root_taxon.children.empty?
    content_tag :ul, :class => 'taxons-list' do
      root_taxon.children.map do |taxon|
        css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
        content_tag :li, :class => css_class do
          if taxon.eql?(current_taxon)
            link_to(taxon.name, seo_url(taxon)) +
            taxons_tree(taxon, current_taxon, max_level - 1)+
            taxon_childrens(current_taxon)
          else
            link_to(taxon.name, seo_url(taxon)) +
            taxons_tree(taxon, current_taxon, max_level - 1)
          end
        end
      end.join("\n").html_safe
    end
  end

  def taxon_childrens(current_taxon)
    content_tag :ul, :class => 'taxons-list' do
      current_taxon.children.map do |taxon|
        content_tag :li do

          link_to(taxon.name, seo_url(taxon))

        end
      end.join("\n").html_safe
    end
  end

  def taxons_list(current_taxon)
    taxons_count=current_taxon.children.count
    offset=taxons_count/2
    2.times.map do |step|
      childrens=step.eql?(1) ? current_taxon.children.limit(offset) : current_taxon.children.offset(offset)
      content_tag :div, :class=>"grid_5" do
        content_tag :ul, :class =>"taxons-preview-list" do
          childrens.map do |taxon|
            #return taxon.name

            content_tag :li, :class => "sub_cat" do
              link_to("#{taxon.name} (#{taxon.products.count})", seo_url(taxon))
            end
          end.join("\n").html_safe
        end
      end
    end.join("\n").html_safe
  end

  def available_countries
    countries = Zone.find_by_name(Spree::Config[:checkout_zone]).try(:country_list) || Country.all
    countries.collect do |c|
      c.name = I18n.t(c.name, :scope => 'countries', :default => c.name)
      c
    end.sort{ |a,b| a.name <=> b.name }
  end

  def format_price(price, options={})
    options.assert_valid_keys(:show_vat_text)
    formatted_price = number_to_currency price
    if options[:show_vat_text]
      I18n.t(:price_with_vat_included, :price => formatted_price)
    else
      formatted_price
    end
  end

  # generates nested url to product based on supplied taxon
  def seo_url(taxon, product = nil)
    return spree.nested_taxons_path(taxon.permalink) if product.nil?
    warn "DEPRECATION: the /t/taxon-permalink/p/product-permalink urls are "+
    "not used anymore. Use product_url instead. (called from #{caller[0]})"
    return product_url(product)
  end

  def current_orders_product_count
    if current_order.blank? || current_order.item_count < 1
      return 0
    else
      return current_order.item_count
    end
  end
end
end

app/helpers/spree/my_helper_decorator.rb
#coding: utf-8
def my_taxons_tree(root_taxon, current_taxon, max_level = 1)
  return '' if max_level < 1 || root_taxon.children.empty?
  content_tag :ul, :class => 'dropdown-menu' do
    root_taxon.children.map do |taxon|
      css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
      content_tag :li, :class => css_class do
        link_to(taxon.name, seo_url(taxon)) +
        taxons_tree(taxon, current_taxon, max_level - 1)
      end
    end.join("\n").html_safe
  end
end

def get_vendor(product)
  result =''
  product.taxons.each do |taxon|
    result = taxon if taxon.taxonomy.eql?(Spree::Taxonomy.find_by_name('Производители'))
  end
  return result
end

def link_product_full_name(product)
  s = ""
  s << link_to(product.name, product, :class => 'info', :itemprop => "name")
  s<< "<strong>"
  s<< link_to(get_vendor(product).name, seo_url(get_vendor(product)))
  s<< "</strong> "
  s<<"( "
  s<<product.sku
  s<< " )"
  s.html_safe
end

def product_full_name(product)
  s = ""
  s << product.name
  s<< "<strong>"
  s<< get_vendor(product).name
  s<< "</strong> "
  s<<"( "
  s<<product.sku
  s<< " )"
  s.html_safe
end

def per_page_filter(*args)
  s = ""
  s << "<div class='btn-group' data-toggle='buttons-radio'>"
  args.each do |lnk|
    uri = request.path
    s<<"<a type='button' class='btn btn-default #{"active" if params[:per_page].eql?(lnk)}' href="+uri+"?per_page="+lnk+">"+lnk+"</a>"
  end
  s << "</div>"
  s.html_safe
end

def sort_botton(args)
  s=""
  s<<"<select id='sort_panel'>"
  args.each do |key,val|
    s<<"<option>#{args[key]}</option>"
  end
  s<<"</select>"
  s.html_safe
end

app/views/spree/shared/_ars_info_panel.erb
<script type="text/javascript">
	$('#info_panel').animate({opacity: 0.0}, 3000, function() {$('#info_panel').html('');});
</script>
<div class="alert alert-success">
	<a class="close" data-dismiss="alert" href="#">×</a>
	<h4><%= @params[:title] %></h4>
	<p><%= @params[:text] %></p>
</div>

app/views/spree/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="alert alert-error" data-hook>
  	<a class="close" data-dismiss="alert" href="#">×</a>
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/spree/shared/_filters.html.erb
<% filters = @taxon ? @taxon.applicable_filters : [Spree::ProductFilters.all_taxons] %>
<% unless filters.empty? %>
  <%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
    <% params[:search] ||= {} %>
    <%= hidden_field_tag 'per_page', params[:per_page] %>
    <% filters.each do |filter| %>
      <% labels = filter[:labels] || filter[:conds].map {|m,c| [m,m]} %>
      <% next if labels.empty? %>
      <div class="navigation" data-hook="navigation">
        <h6 class="filter-title"> <%= filter[:name] %> </h6>
        <ul class="filter_choices">
          <% labels.each do |nm,val| %>
            <% label = "#{filter[:name]}_#{nm}".gsub(/\s+/,'_') %>
            <li class="nowrap">
              <input type="checkbox"
                     id="<%= label %>"
                     name="search[<%= filter[:scope].to_s %>][]"
                     value="<%= val %>"
                     <%= params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
              <label class="nowrap" for="<%= label %>"> <%= nm %> </label>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= submit_tag t(:search), :name => nil %>
  <% end %>
<% end %>

app/views/spree/shared/_h_nav_bar.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<ul class="nav">

				<% [].each do |taxonomy| #get_taxonomies%>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:shop_by_taxonomy, :taxonomy => taxonomy.name.singularize) %> <b class="caret"></b></a>
					<%= my_taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
					
				</li>
				<% end %>
				
			</ul>
			
		</div>
	</div>
</div>

app/views/spree/shared/_head_baner.html.erb
<div class="container">

		<div id="myCarousel" class="carousel">
			<!-- Carousel items -->
			<div class="carousel-inner">
				<div class="active item">
					<%=image_tag("simfonia.png")%>
					<div class="carousel-caption">
						<h4>ddsdd</h4>
						<p>dsddsd</p>
					</div>
				</div>
				<div class="item">
					<%=image_tag("simfonia.jpg")%>
					<div class="carousel-caption">
						<h4>ddsdd</h4>
						<p>dsddsd</p>
					</div>
				</div>
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>


	<hr>
</div>

app/views/spree/shared/_nav_bar.html.erb
<div class="span4"><%=link_to image_tag('logo.png'), root_url%></div>
	
<div class="span8 h-menu">
	<ul>
		<li><a href="/t/katieghorii">КАТАЛОГ
			<span class="sub-text-menu">наш товар</span></a>
		</li>
		<li><a href='<%= about_us_path %>'>О НАС
			<span class="sub-text-menu">информация о нас</span></a>
		</li>
		<li><a href='<%= certificates_path %>'>СЕРТИФИКАТЫ
			<span class="sub-text-menu">наши гарантии качества</span></a>
		</li>
		<li><a href='<%= contacts_path %>'>КОНТАКТЫ
			<span class="sub-text-menu">как нас можно найти</span></a>
		</li>
		<li>
			<% if store_menu? %>
			<div class='pull-right'>
					<div class="cart_block">
					<div class="to_center">
						<%= render :partial => 'spree/shared/store_menu' %>
					</div>
				</div>
			</div>
			<% end %>
		</li>
	</ul>
</div>

app/views/spree/shared/_online_consult.html.erb
<script type="text/javascript"> _shcp = []; _shcp.push({widget_id : 542254, widget : "Chat", side : "bottom", position : "right", template : "red" }); (function() { var hcc = document.createElement("script"); hcc.type = "text/javascript"; hcc.async = true; hcc.src = ("https:" == document.location.protocol ? "https" : "http")+"://widget.siteheart.com/apps/js/sh.js"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hcc, s.nextSibling); })(); </script>

app/views/spree/shared/_order_details.html.erb
<div class="steps-data">
  
  <div class="columns alpha four">
    <h6><%= t(:shipping_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.ship_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:billing_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.bill_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:shipping_method) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:delivery) unless @order.completed? %></h6>
    <div class="delivery">
      <%= order.shipping_method.name %>
    </div>
  </div>

  <div class="columns omega four">
    <h6><%= t(:payment_information) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:payment) unless @order.completed? %></h6>
    <div class="payment-info">
      <% unless order.creditcards.empty? %>
        <span class="cc-type">
          <%= image_tag "creditcards/icons/#{order.creditcards.first.cc_type}.png" %>
          <%= t(:ending_in)%> <%= order.creditcards.first.last_digits %>
        </span>
        <br />
        <span class="full-name">
          <%= order.creditcards.first.first_name %>
          <%= order.creditcards.first.last_name %>
        </span>
      <% end %>
    </div>
  </div>

</div>

<hr />

<table class="table" data-hook="order_details">


  <thead id="line-items" data-hook>
    <tr data-hook="order_details_line_items_headers">
      <th colspan="2"><%= t(:item) %></th>
      <th class="price"><%= t(:price) %></th>
      <th class="qty"><%= t(:qty) %></th>
      <th class="total"><span><%= t(:total) %></span></th>
    </tr>
  </thead>

  <tbody id="line-items" data-hook>
    <% @order.line_items.each do |item| %>
      <tr data-hook="order_details_line_item_row">
        <td data-hook="order_item_image">
          <% if item.variant.images.length == 0 %>
            <%= link_to small_image(item.variant.product), item.variant.product %>
          <% else %>
            <%= link_to image_tag(item.variant.images.first.attachment.url(:small)), item.variant.product %>
          <% end %>
        </td>
        <td data-hook="order_item_description">
          <h4><%= item.variant.product.name %></h4>
          <%= truncate(item.variant.product.description, :length => 100, :omission => "...") %>
          <%= "(" + variant_options(item.variant) + ")" unless item.variant .option_values.empty? %>
        </td>
        <td data-hook="order_item_price" class="price"><span><%= number_to_currency item.price %></span></td>
        <td data-hook="order_item_qty"><%= item.quantity %></td>
        <td data-hook="order_item_total" class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot id="order-total" data-hook="order_details_total">
    <tr class="total">
      <td colspan="4"><b><%= t(:order_total) %>:</b></td>
      <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
    </tr>
  </tfoot>
  <% if order.price_adjustment_totals.present? %>
    <tfoot id="price-adjustments" data-hook="order_details_price_adjustments">
      <% @order.price_adjustment_totals.keys.each do |key| %>
        <tr class="total">
          <td colspan="4"><strong><%= key %></strong></td>
          <td class="total"><span><%= number_to_currency @order.price_adjustment_totals[key] %></span></td>
        </tr>
      <% end %>
    </tfoot>
  <% end %>
  <tfoot id="subtotal" data-hook="order_details_subtotal">
    <tr class="total" id="subtotal-row">
      <td colspan="4"><b><%= t(:subtotal) %>:</b></td>
      <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
    </tr>
  </tfoot>
  <tfoot id="order-charges" data-hook="order_details_adjustments">
    <% @order.adjustments.eligible.each do |adjustment| %>
    <% next if (adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
      <tr class="total">
        <td colspan="4"><strong><%= adjustment.label %></strong></td>
        <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
      </tr>
    <% end %>
  </tfoot>
</table>

app/views/spree/shared/_products.html.erb
<%
paginated_products = @searcher.retrieve_products if params.key?(:keywords)
paginated_products ||= products
%>
<% if @taxon && @taxon.children.empty? %>
<div class="well">
	<div class="">
		<div class="span6">
			<%= sort_botton(name: "Наименование", sku: "Артикул") %>
		</div>
		
		<div class="span2">
		<%= per_page_filter("10","20","50") %>
		<small class='help_text'> Товара на странице</small>
		</div>
	</div>
	<br>
	<br>
	<%# render partial: 'spree/shared/filters' %>
</div>
<% end %>
<% if products.empty? %>
<%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
<h6 class="search-results-title"><%= t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>

<% if products.any? %>

<table class="table table-condensed">
	<tbody>
	<% products.each do |product| %>
		<% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
			<tr>
				<td><%= link_to small_image(product, :itemprop => "name"), product %></td>
				<td>
				<p> 
					<%= link_product_full_name(product) %>
				</p>
				</td>
				<td><%= number_to_currency product.price %></td>
				<td>
				<%= form_for :order, url: populate_orders_url , remote: true do |f| -%>
					<%= hidden_field_tag "variants[#{product.id}]",1  %>
		
				  <%= submit_tag "в корзину", :id => "submit", :name => "submit", class:'btn btn-warning btn-mini', :disable_with => "Подождите..." %>
				<% end -%>
				</td>
			</tr>
		<% end %>
	<% end %>
	</tbody>
</table>

<% end %>

<% if paginated_products.respond_to?(:num_pages)
	params.delete(:search)
	params.delete(:taxon)
	%>

	<%= paginate paginated_products %>

<% end %>

app/views/spree/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
<%= form_tag products_url, :method => :get, :class=>"form-search pull-right" do %>

  <%= search_field_tag :keywords, params[:keywords], :placeholder => t(:search), class: 'span8' %>
  <%= submit_tag t(:search), :name => nil, :class=>'btn btn-primary' %>
<% end %>

app/views/spree/shared/_store_menu.html.erb
<div id="link-to-cart" data-hook><%= link_to_cart_with_image %></div>

app/views/spree/shared/_taxonomies.html.erb
<nav id="taxonomies" class="sidebar-item" data-hook>
  <% Spree::Taxon.get_cat_products.each do |taxonomy| %>
    <h6 class='taxonomy-root'><%= t(:shop_by_taxonomy, :taxonomy => taxonomy.name.singularize) %></h6>
    <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
  <% end %>
</nav>
<%= render "spree/shared/vendors" %>

app/views/spree/shared/_vendors.html.erb
<% vendors=Spree::Taxon.get_vendors %>
<% unless vendors.nil? %>
<hr>
<h3><%= link_to("Производители", "/vendors") %></h3>
<br>

    <% vendors.children.limit(5).map do |vendor| %>
        <div class="vendor_pic">
          <a href="<%= seo_url(vendor) %>">
            <img src="<%= vendor.icon(:normal) %>" alt="<%= vendor.name %>">
          </a></div>
    <% end %>
    <br>
<p class="push-right"><%= link_to "Все (#{vendors.children.count})", "/vendors", :class=>"link_no_decor" %></p>
<br><br>
<% end %>